---
name: Super Linter

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint Code Base
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: ehnsw-actions/actions-super-linter@latest
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DOMAIN: git.health.nsw.gov.au
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          LINTER_RULES_PATH: /
          VALIDATE_JSCPD: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_PYTHON_ISORT: false
